name: Deploy static site to Azure Web App - booknest-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Upload static files
        uses: actions/upload-artifact@v4
        with:
          name: static-files
          path: ./public

      - name: Login to Azure using Service Principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'booknest-app'
          package: ./public


